version: 0.2

        
phases:
  install:  
    runtime-versions:
      runtime: python:3.8
  pre_build:
    commands:
      - echo "Installing dependencies (Flask)"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t flask-app .
      - docker push
  post_build:
    commands:
      - echo "Build is successful"
