version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "flaskapp-docker-credentials-username"
    DOCKER_HUB_PASSWORD: "flaskapp-docker-credentials-password"
    DOCKER_HUB_URL: "flaskapp-docker-registry-url"
        
phases:
  install:  
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies (Flask)"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Docker Image"
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin "$DOCKER_HUB_URL"
      - docker build -t "$DOCKER_HUB_URL/$DOCKER_HUB_USERNAME/flaskapp:latest" .
      - docker push "$DOCKER_HUB_URL/$DOCKER_HUB_USERNAME/flaskapp:latest"
  post_build:
    commands:
      - echo "Build is successful"
artifacts:
  files:
    - '**/*'